defmodule Mix.Tasks.Compile.FwInitUnits do
  use Mix.Task.Compiler

  @shortdoc "Generates init unit files for the detected init system"

  @moduledoc """
  Mix compiler task that detects the running init system and writes
  the appropriate service unit files into `priv/init/` after every
  `mix compile`.

  Supported init systems (detected in order):

    1. **systemd** — detected via `/run/systemd/private` or
       `INVOCATION_ID` env var.  Writes a user unit file to
       `priv/init/systemd/fw.service`.

    2. **runit** — detected via `/run/runit` or `/sbin/runit-init`.
       Writes `priv/init/runit/fw/{run,finish,log/run}`.

    3. **s6** — detected via `/run/s6` or `s6-svscan` in PATH.
       Writes `priv/init/s6/fw/{run,finish,log/run}` using execlineb.

  If no supported init is detected the task prints a warning and exits
  cleanly without failing the build.

  The generated files are templates — replace placeholder values
  (e.g. `YOURUSER`, release path) before installing.
  See `priv/init/README.md` for install instructions.
  """

  # Path where unit files are written inside the project tree.
  @priv_init "priv/init"

  @impl true
  def run(_args) do
    init = detect_init()
    Mix.shell().info("[fw_init_units] detected init system: #{init}")
    generate(init)
  end

  # ---------------------------------------------------------------------------
  # Init detection
  # ---------------------------------------------------------------------------

  defp detect_init do
    cond do
      systemd?() -> :systemd
      runit?() -> :runit
      s6?() -> :s6
      true -> :unknown
    end
  end

  defp systemd? do
    File.exists?("/run/systemd/private") or
      System.get_env("INVOCATION_ID") != nil or
      String.contains?(pid1_comm(), "systemd")
  end

  defp runit? do
    File.exists?("/run/runit") or
      File.exists?("/sbin/runit-init") or
      String.contains?(pid1_comm(), "runit")
  end

  defp s6? do
    File.exists?("/run/s6") or
      System.find_executable("s6-svscan") != nil or
      String.contains?(pid1_comm(), "s6")
  end

  # Read /proc/1/comm for the PID-1 process name (Linux only).
  defp pid1_comm do
    case File.read("/proc/1/comm") do
      {:ok, comm} -> String.trim(comm)
      _ -> ""
    end
  end

  # ---------------------------------------------------------------------------
  # File generation
  # ---------------------------------------------------------------------------

  defp generate(:unknown) do
    Mix.shell().info(
      "[fw_init_units] WARNING: could not detect a supported init system " <>
        "(systemd / runit / s6). Skipping unit generation. " <>
        "Templates are available in priv/init/."
    )

    write_readme()
    write_templates_all()
    {:ok, []}
  end

  defp generate(init) do
    write_readme()
    write_templates_all()

    case init do
      :systemd -> write_systemd()
      :runit -> write_runit()
      :s6 -> write_s6()
    end

    Mix.shell().info("[fw_init_units] unit files written to #{@priv_init}/#{init}/")
    {:ok, []}
  end

  # ---------------------------------------------------------------------------
  # systemd
  # ---------------------------------------------------------------------------

  defp write_systemd do
    dir = Path.join([@priv_init, "systemd"])
    :ok = File.mkdir_p(dir)

    write_file(Path.join(dir, "fw.service"), systemd_unit())
  end

  defp systemd_unit do
    """
    # ~/.config/systemd/user/fw.service
    #
    # Generated by `mix compile` via Mix.Tasks.Compile.FwInitUnits.
    # Install:
    #   mkdir -p ~/.config/systemd/user
    #   cp priv/init/systemd/fw.service ~/.config/systemd/user/fw.service
    #   systemctl --user daemon-reload
    #   systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR
    #   systemctl --user enable --now fw
    #   journalctl --user -u fw -f
    #
    # Adjust ExecStart to the path of your installed OTP release.
    # Build the release first: mix release

    [Unit]
    Description=fw — feature-wallpaper Wayland wallpaper daemon
    Documentation=https://github.com/Skartorion/feature-wallpaper
    After=graphical-session.target
    PartOf=graphical-session.target

    [Service]
    Type=simple

    # Path to the compiled OTP release binary (adjust as needed)
    ExecStart=%h/.local/opt/fw/bin/fw start
    ExecStop=%h/.local/opt/fw/bin/fw stop

    KillSignal=SIGTERM
    KillMode=mixed
    TimeoutStopSec=10

    Restart=on-failure
    RestartSec=3s

    # WAYLAND_DISPLAY is inherited from the compositor session.
    # Run once after login to propagate it:
    #   systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR
    Environment=LANG=en_US.UTF-8

    StandardOutput=journal
    StandardError=journal
    SyslogIdentifier=fw

    [Install]
    WantedBy=graphical-session.target
    """
  end

  # ---------------------------------------------------------------------------
  # runit
  # ---------------------------------------------------------------------------

  defp write_runit do
    base = Path.join([@priv_init, "runit", "fw"])
    log_dir = Path.join(base, "log")
    :ok = File.mkdir_p(log_dir)

    write_file(Path.join(base, "run"), runit_run(), mode: 0o755)
    write_file(Path.join(base, "finish"), runit_finish(), mode: 0o755)
    write_file(Path.join(log_dir, "run"), runit_log_run(), mode: 0o755)
  end

  defp runit_run do
    """
    #!/bin/sh
    # /etc/sv/fw/run  — runit service run script
    #
    # Generated by `mix compile` via Mix.Tasks.Compile.FwInitUnits.
    # Install:
    #   sudo cp -r priv/init/runit/fw /etc/sv/fw
    #   sudo ln -s /etc/sv/fw /var/service/fw
    #   sv status fw
    #
    # Adjust the install path and UID below.

    INSTALL_PATH=/opt/fw
    FW_USER=YOURUSER
    FW_UID=$(id -u "${FW_USER}" 2>/dev/null || echo 1000)

    exec chpst -u "${FW_USER}:${FW_USER}" \\
      env WAYLAND_DISPLAY=wayland-1 \\
          XDG_RUNTIME_DIR=/run/user/${FW_UID} \\
      "${INSTALL_PATH}/bin/fw" start
    """
  end

  defp runit_finish do
    """
    #!/bin/sh
    # Called by runit when the service exits.
    # $1 = exit code, $2 = signal (-1 if exited without a signal)
    echo "[fw] exited: code=$1 signal=$2" >&2
    """
  end

  defp runit_log_run do
    """
    #!/bin/sh
    # Log consumer for runit — pipes stdout/stderr through svlogd.
    exec svlogd -tt /var/log/fw
    """
  end

  # ---------------------------------------------------------------------------
  # s6
  # ---------------------------------------------------------------------------

  defp write_s6 do
    base = Path.join([@priv_init, "s6", "fw"])
    log_dir = Path.join([@priv_init, "s6", "fw-log"])
    :ok = File.mkdir_p(base)
    :ok = File.mkdir_p(log_dir)

    write_file(Path.join(base, "run"), s6_run(), mode: 0o755)
    write_file(Path.join(base, "finish"), s6_finish(), mode: 0o755)
    write_file(Path.join(base, "type"), "longrun\n")
    write_file(Path.join(log_dir, "run"), s6_log_run(), mode: 0o755)
    write_file(Path.join(log_dir, "type"), "longrun\n")
  end

  defp s6_run do
    """
    #!/bin/execlineb -P
    # s6 service run script for fw
    #
    # Generated by `mix compile` via Mix.Tasks.Compile.FwInitUnits.
    # Install into your s6 service directory, e.g.:
    #   sudo cp -r priv/init/s6/fw /etc/s6/sv/fw
    #   sudo cp -r priv/init/s6/fw-log /etc/s6/sv/fw-log
    # Then add to your s6-rc source database or symlink into the scan dir.
    #
    # Adjust INSTALL_PATH and FW_USER below.

    # Import Wayland display from environment (set by compositor or import-env)
    importas -D "wayland-1" WAYLAND_DISPLAY WAYLAND_DISPLAY
    importas -D "/run/user/1000" XDG_RUNTIME_DIR XDG_RUNTIME_DIR

    # Drop privileges to the fw user
    s6-setuidgid YOURUSER

    # Exec the OTP release (stays in foreground — correct for s6)
    /opt/fw/bin/fw start
    """
  end

  defp s6_finish do
    """
    #!/bin/execlineb
    # Called when the service exits.
    # $1 = exit code, $2 = signal
    foreground { s6-echo "[fw] service exited" }
    exit 0
    """
  end

  defp s6_log_run do
    """
    #!/bin/execlineb -P
    # s6-log consumer for fw
    s6-log -d3 T /var/log/fw
    """
  end

  # ---------------------------------------------------------------------------
  # Shared templates (written regardless of detected init)
  # ---------------------------------------------------------------------------

  defp write_templates_all do
    # Write all templates so users on any init system have them available.
    # Already generated for the detected system; here we just ensure the
    # other managers' directories exist with their files too.
    :ok
  end

  # ---------------------------------------------------------------------------
  # README
  # ---------------------------------------------------------------------------

  defp write_readme do
    :ok = File.mkdir_p(@priv_init)
    write_file(Path.join(@priv_init, "README.md"), readme())
  end

  defp readme do
    """
    # fw — Init Unit Files

    This directory is generated by `mix compile` via
    `Mix.Tasks.Compile.FwInitUnits`. The task detects the running init
    system and writes the appropriate service unit files here.

    ## Supported init systems

    | Init | Generated path | Detection method |
    |------|---------------|------------------|
    | systemd | `priv/init/systemd/fw.service` | `/run/systemd/private`, `INVOCATION_ID` env, or PID-1 name |
    | runit | `priv/init/runit/fw/{run,finish,log/run}` | `/run/runit`, `/sbin/runit-init`, or PID-1 name |
    | s6 | `priv/init/s6/fw/{run,finish,type}` + `fw-log/` | `/run/s6`, `s6-svscan` in PATH, or PID-1 name |

    Files are regenerated on every `mix compile`. They are templates —
    replace placeholder values (YOURUSER, install paths) before
    installing.

    ## systemd (recommended for Hyprland / sway)

    ```bash
    # Build the OTP release
    mix release
    mkdir -p ~/.local/opt/fw
    cp -r _build/prod/rel/fw/. ~/.local/opt/fw/

    # Install the user unit
    mkdir -p ~/.config/systemd/user
    cp priv/init/systemd/fw.service ~/.config/systemd/user/fw.service

    # Reload and propagate Wayland env
    systemctl --user daemon-reload
    systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR

    # Enable and start
    systemctl --user enable --now fw
    journalctl --user -u fw -f
    ```

    ## runit (Void Linux, artix-runit, etc.)

    ```bash
    # Edit run script: set FW_USER and INSTALL_PATH
    nano priv/init/runit/fw/run

    sudo cp -r priv/init/runit/fw /etc/sv/fw
    sudo ln -s /etc/sv/fw /var/service/fw
    sv status fw
    ```

    ## s6 (artix-s6, Chimera Linux, etc.)

    ```bash
    # Edit run script: set YOURUSER and install path
    nano priv/init/s6/fw/run

    sudo cp -r priv/init/s6/fw /etc/s6/sv/fw
    sudo cp -r priv/init/s6/fw-log /etc/s6/sv/fw-log
    # Add to your s6-rc source database or symlink into the scan dir.
    ```

    ## Notes

    - The OTP release binary (`bin/fw start`) runs in the **foreground**,
      which is exactly what all three supervisors expect.
    - `KillSignal=SIGTERM` / `SIGTERM` in runit/s6 lets OTP shut down
      supervision trees gracefully before the VM exits.
    - For Hyprland, add to `hyprland.conf`:
      `exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_RUNTIME_DIR`
    """
  end

  # ---------------------------------------------------------------------------
  # Helpers
  # ---------------------------------------------------------------------------

  defp write_file(path, content, opts \\ []) do
    :ok = File.mkdir_p(Path.dirname(path))
    :ok = File.write(path, content)

    case Keyword.get(opts, :mode) do
      nil -> :ok
      mode -> File.chmod!(path, mode)
    end
  end
end
